/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Inline_response_200
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Details of my aspirational car
   * 
   * Expected answers:
   *   code 200 : Inline_response_200 (OK)
   */
  def vehicleGet(): ApiRequest[Inline_response_200] =
    ApiRequest[Inline_response_200](ApiMethods.GET, "https://virtserver.swaggerhub.com/SmartBear_Software/Tesla_API/0.0.1", "/vehicle", "application/json")
      .withSuccessResponse[Inline_response_200](200)
      

}

